{
 "title": "gestao_vendas",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Categorias Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\",uri=\"/categorias\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}{{uri}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\",uri=\"/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}{{uri}}"
    }
   ]
  },
  {
   "title": "Produtos count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/categoria{codigoCategoria}/produtos\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}{{uri}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/categoria{codigoCategoria}/produtos/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}{{uri}}"
    }
   ]
  },
  {
   "title": "Categorias Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/categorias\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}{{uri}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/categorias/{id}\"}",
     "legendFormat": "{{{{method}}/{{outcome}}/{{status}}{{uri}}}}"
    }
   ]
  },
  {
   "title": "Produtos max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/categoria{codigoCategoria}/produtos\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}{{uri}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/categoria{codigoCategoria}/produtos/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}{{uri}}"
    }
   ]
  }
 ]
}